# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: "242c63fa-cb21-4f7a-a7ac-5f8bbf566662"
  # image names
  imageApiRepository: "apiimage"
  imageClientRepository: "clientimage"
  # docker file paths
  containerRegistry: "recipeapis.azurecr.io"
  dockerfileApiPath: "./deploy/DockerfileApi"
  dockerfileClientPath: "./deploy/DockerfileClient"
  dockerComposeFile: "./docker-compose.yaml"
  # container names + resource groups
  clientContainerName: "client"
  clientPort: 80
  apiContainerName: "api"
  resourceGroup: "CookingApp"
  projectFolder: "."
  tag: "latest"
  registryUsername: "RecipeAPIs"
  registryPassword: "uMae5efq4tOfYIqlPefk1nJp/WK=Y0/t"
  dnsLabel: "client"

  # Agent VM image name
  vmImageName: "ubuntu-latest"
  agentPool: "Deploy Agents"

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build
        pool: $(agentPool)
        steps:
          - task: Docker@2
            displayName: Build and push Client image to container registry
            inputs:
              command: buildAndPush
              repository: $(imageClientRepository)
              buildContext: $(projectFolder)
              dockerfile: $(dockerfileClientPath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
          - task: Docker@2
            displayName: Build and push API image to container registry
            inputs:
              command: buildAndPush
              repository: $(imageApiRepository)
              buildContext: $(projectFolder)
              dockerfile: $(dockerfileApiPath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: |
                $(tag)
          - task: Bash@3
            displayName: Delete Client Container 
            inputs:
              targetType: 'inline'
              script: 'az container delete --name $(clientContainerName) --resource-group $(resourceGroup) --yes'
          - task: Bash@3
            displayName: Create Client Container
            inputs:
              targetType: 'inline'
              script: 'az container create --name $(clientContainerName) --resource-group $(resourceGroup) --image $(containerRegistry)/$(imageClientRepository):$(tag) --registry-login-server $(containerRegistry) --registry-username $(registryUsername) --registry-password $(registryPassword) --dns-name-label $(dnsLabel) --port $(clientPort)'
