apiVersion: v1
kind: Service
metadata:
  name: recipe-service
  labels:
    app: recipe-service
spec:
  type: LoadBalancer
  ports:
    - port: 80 # port number that is exposed within the cluster
      name: recipe-api
      targetPort: 50150 # ports that containers are listening on
  selector:
    app: recipeapp # forward requests to pod's with label of this value
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: recipeapp
  template:
    metadata:
      labels:
        app: recipeapp
    spec:
      containers:
        - name: api-container
          image: yuxuanleoli/recipe-backend:1.0
          ports:
            - containerPort: 50150
